name: Application deployment

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Select service to build and deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - backend
          - inference
          - frontend

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- BACKEND ---
      - name: Build and Push Backend
        if: github.event.inputs.service == 'backend' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v5
        with:
          context: ./fastapi
          push: true
          tags: ${{ env.DOCKER_USER }}/app-backend:latest,${{ env.DOCKER_USER }}/app-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- INFERENCE ---
      - name: Build and Push Inference
        if: github.event.inputs.service == 'inference' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v5
        with:
          context: ./inference_service
          push: true
          tags: ${{ env.DOCKER_USER }}/app-inference:latest,${{ env.DOCKER_USER }}/app-inference:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- FRONTEND ---
      - name: Build and Push Frontend
        if: github.event.inputs.service == 'frontend' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ${{ env.DOCKER_USER }}/app-frontend:latest,${{ env.DOCKER_USER }}/app-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max