services:
  backend:
    build:
      context: fastapi
      dockerfile: Dockerfile
    container_name: api
    image: olomg48/api:latest
    ports:
      - 8000:8000
    networks:
      - network_dev

  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: front
    image: olomg48/front:latest
    ports:
      - 8080:8080
    networks:
      - network_dev

  inference:
    build:
      context: inference_service
      dockerfile: Dockerfile
    container_name: inference
    image: olomg48/inference:latest
    ports:
      - 8001:8000
    networks:
      - network_dev
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlartifacts:/mlartifacts

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - 5000:5000
    networks:
      - network_dev
    working_dir: /mlflow
    command: >
      bash -c "pip install boto3 && mlflow server 
      --backend-store-uri sqlite:///mlflow.db 
      --artifacts-destination s3://mlflow-bucket/
      --host 0.0.0.0
      --allowed-hosts "mlflow:5000,localhost:5000,127.0.0.1:5000,169.254.53.144:5000"
      --serve-artifacts
    environment:
      - MLFLOW_HTTP_LINES_ALLOWED_HOSTS=mlflow,localhost,127.0.0.1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_S3_IGNORE_CONFIG_FILE=true

  minio:
    image: minio/minio
    container_name: minio
    networks:
      - network_dev
    ports:
      - "9000:9000" # API
      - "9001:9001" # Konsola UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

networks:
  network_dev:
    driver: bridge
