{{- range $appName, $appConfig := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-deployment
  labels:
    app: {{ $appName }}
spec:
  replicas: {{ $appConfig.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
      - name: {{ $appName }}
        image: {{ $appConfig.deploy.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ $appConfig.deploy.containerPort }}

        {{- if $appConfig.deploy.args }}
        args:
          {{- toYaml $appConfig.deploy.args | nindent 10 }}
        {{- end }}

        {{- if $appConfig.deploy.resources }}
        resources:
          {{- toYaml $appConfig.deploy.resources | nindent 10 }}
        {{- end }}

        {{- if or $appConfig.deploy.env $appConfig.deploy.secretEnv }}
        env:
          {{- /* Zwykłe zmienne */ -}}
          {{- range $key, $value := $appConfig.deploy.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          
          {{- /* Zmienne z secretów */ -}}
          {{- range $key, $val := $appConfig.deploy.secretEnv }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $val.secretName }}
                key: {{ $val.secretKey }}
          {{- end }}

        {{- end }}
{{- end }}