{{- range $appName, $appConfig := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-srv
  labels:
    monitor: prometheus
spec:
  selector:
    app: {{ $appName }}
  ports:
    - name: {{ $appConfig.service.portName}}
      port: {{ $appConfig.service.port }}
      targetPort: {{ $appConfig.service.targetPort }}
      nodePort: {{ $appConfig.service.nodePort }}
  type: NodePort
{{- end }}