apiVersion: v2
name: app-helm
description: app-helm description
type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: minio
    version: 5.4.0 
    repository: https://charts.min.io/
