name: Application deployment

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Select service to build and deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - backend
          - inference
          - frontend

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- BACKEND ---
      - name: Build and Push Backend
        if: github.event.inputs.service == 'backend' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v5
        with:
          context: ./fastapi
          push: true
          tags: ${{ env.DOCKER_USER }}/api:latest,${{ env.DOCKER_USER }}/api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update values for Backend 
        if: github.event.inputs.service == 'backend' || github.event.inputs.service == 'all'
        run: |
          yq -i '.apps.api.deploy.image = "olomg48/api:${{ github.sha }}"' ./infra/app-helm/values.yaml

      # --- INFERENCE ---
      - name: Build and Push Inference
        if: github.event.inputs.service == 'inference' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v5
        with:
          context: ./inference_service
          push: true
          tags: ${{ env.DOCKER_USER }}/inference:latest,${{ env.DOCKER_USER }}/inference:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Update values for inference 
        if: github.event.inputs.service == 'inference' || github.event.inputs.service == 'all'
        run: |
          yq -i '.apps.inference.deploy.image = "olomg48/inference:${{ github.sha }}"' ./infra/app-helm/values.yaml

      # --- FRONTEND ---
      - name: Build and Push Frontend
        if: github.event.inputs.service == 'frontend' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ${{ env.DOCKER_USER }}/front:latest,${{ env.DOCKER_USER }}/front:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update values for Backend 
        if: github.event.inputs.service == 'frontend' || github.event.inputs.service == 'all'
        run: |
          yq -i '.apps.front.deploy.image = "olomg48/front:${{ github.sha }}"' ./infra/app-helm/values.yaml

      - name: update repository
        run: | 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update images versions after build ${{ github.sha }} [skip ci]"
          git push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login into aks cluster
        run: |
          az aks get-credentials --resource-group olek-aks-rg --name olek-aks-cluster

      - name: Helm dependencies and namespace
        run: |
          helm dependency update ./infra/app-helm
          kubectl create namespace application --dry-run=client -o yaml | kubectl apply -f -

      - name: Helm deploy app
        run: |
            kubectl create secret generic connection-string --namespace application \
            --from-literal=string='${{ secrets.DB_PASSWORD }}' \
            --dry-run=client -o yaml | kubectl apply -f -          
            helm upgrade --install app-helm ./infra/app-helm --namespace application --create-namespace \
            -f ./infra/app-helm/values.yaml -f ./infra/app-helm/third_party_charts_values.yaml